### ISSUE TITLE
运行出错

### ISSUE THREAD

**Issue by ohohjhhh** [Marve1ous/NeuralStyle#6]
您好，请问在运行这个项目过程中，出现这个错误是什么意思呢？该怎么解决？谢谢！！

**Comment by ohohjhhh** [comment]
ERROR in app: Exception on /get [GET]
Traceback (most recent call last):
  File "D:\Anaconda\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\Anaconda\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\Anaconda\lib\site-packages\flask_cors\extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "D:\Anaconda\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "D:\Anaconda\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "D:\Anaconda\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\Anaconda\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "F:\QianYi\NeuralStyle-master\app.py", line 46, in get
    s = f2.split('/')[2].split('.')[0] + '_' + f1.split('/')[2]
IndexError: list index out of range
127.0.0.1 - - [28/Mar/2021 11:39:51] "GET /get?f1=staticcontentcorgi.jpg&f2=static/style/style5.jpg HTTP/1.1" 500 -

**Comment by ohohjhhh** [comment]
图片发不出来

**Comment by Marve1ous** [comment]
s = f2.split('/')[2].split('.')[0] + '_' + f1.split('/')[2]
这个地方是截取图片名称
`f1=staticcontentcorgi.jpg&f2=static/style/style5.jpg` 这个地方可以看出你的f1是没有'/'的，所以截取报错
